Added a helpful comment in main.py
kaustubh-vats/javascript-fun pull request #4
Opened 2022-10-28 16:28 UTC by pranavgoel29

2022-10-29 02:04 UTC, kaustubh-vats requested changes

2022-10-29 02:04 UTC, kaustubh-vats commented on main.py
> +from xml.etree.ElementTree import Comment
Why this import?

2022-10-29 10:19 UTC, pranavgoel29 commented on main.py
> +from xml.etree.ElementTree import Comment
I have imported anything

2022-10-30 03:46 UTC, kaustubh-vats approved these changes

2022-10-30 03:46 UTC, kaustubh-vats approved these changes

2022-10-30 03:46 UTC, merged